### ISSUE TITLE
Do not ignore a zope mapping

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#100]
#99 was not enough 😖 😓 

Now with `2.9` all packages get reported and `Zope` does not longer hide `zope.schema` 👍🏾 

But unfortunately, if one provides a mapping on `pyproject.toml` like:

```toml
[tool.dependencychecker]
Zope = ["ZTUtils", "Products.Five"]
```

It is ignored and `ZTUtils` and `Products.Five` imports are still considered not missing requirements 😕 

I will look at a fix for it.

_Fortunately_ the very first package that I was trying `z3c.dependencychecker` already made me discover #98 and now this one 🍀 😄
